import Link from "next/link";
import "./globals.scss";

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body>
                <div className="sidebar">
                    <Link href="/">Home</Link>
                    <Link href="/list">List</Link>
                    <Link href="/write">Write</Link>
                </div>
                {children}
            </body>
        </html>
    );
}
